_target_: proteindiff.utils.cfg_utils.model_cfg_utils.SimpleProteinDiffCfg

d_model: 64
d_latent: 16
voxel_dim: 8
cell_dim: 1.0
t_max: 100
n_mpnn_blocks: 1
n_transformer_blocks: 1
n_dit_blocks: 1
n_heads: 8
