defaults:
  - /model: default
  - /data: default
  - /logger: default
  - /losses: default
  - /optim: default
  - /scheduler: default
  - /profiler: default
  - hydra
  - _self_

_target_: proteindiff.training.train.training_run.TrainingRunCfg

# training params
train_stage: vae
max_steps: 5000
val_interval: 1000
accumulation_steps: 8
grad_clip_norm: 5.0
compile_model: true
load_from_checkpoint: ""
checkpoint_interval: 500
