hydra:
  run:
    dir: /home/jaime/Desktop/scratch/experiments/run/${now:%Y-%m-%d}/${now:%H-%M-%S}

  sweep:
    dir: /home/jaime/Desktop/scratch/experiments/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.override_dir}
