_target_: proteindiff.training.losses.TrainingRunLossesCfg

train_type: vae

loss_fn:
  _target_: proteindiff.training.losses.LossFnCfg
  seq_lbl_smooth: 0.0
  kl_div_weight: 0.0
  div_mse_weight: 0.0
  seq_weight: 0.0
  distogram_weight: 1.0
  anglogram_weight: 0.0
  dist_weight: 1.0
  angle_weight: 1.0
  plddt_weight: 1.0
  pae_weight: 1.0
  dist_range: [2.0, 22.0]
